version: '3.7'

services:
 
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306  

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
    - "mysql:db"
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
      
  course-work:
    container_name: course-work
    depends_on: 
    - mysql
    image: muditha101/course-work:v1.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "8081:8080"
    volumes:
      - db_data:/var/lib/app
      

volumes:
    db_data: